// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using album_collection.Models;

namespace album_collection.Migrations
{
    [DbContext(typeof(AlbumCollectionContext))]
    [Migration("20200325174633_SongLinksAndImages")]
    partial class SongLinksAndImages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            ArtistId = 1,
                            Image = "Mumfordsonssighnomore.jpg",
                            RecordLabel = "Island Records",
                            Title = "Sigh No More"
                        },
                        new
                        {
                            AlbumId = 2,
                            ArtistId = 1,
                            Image = "Babelcoverart.jpg",
                            RecordLabel = "Island Records",
                            Title = "Babel"
                        },
                        new
                        {
                            AlbumId = 3,
                            ArtistId = 2,
                            Image = "lacuna_unleashed_album.jpg",
                            RecordLabel = "Century Media",
                            Title = "Unleashed Memories"
                        },
                        new
                        {
                            AlbumId = 4,
                            ArtistId = 2,
                            Image = "lacuna_coma_album.jpg",
                            RecordLabel = "Century Media",
                            Title = "Comalies"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hometown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            Hometown = "London, UK",
                            Image = "mumfordsons.jpg",
                            Name = "Mumford & Sons"
                        },
                        new
                        {
                            ArtistId = 2,
                            Hometown = "Milan, Italy",
                            Image = "lacuna_band.jpg",
                            Name = "Lacuna Coil"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Links")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SongTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SongId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            AlbumId = 1,
                            Duration = "3:30",
                            Links = "https://www.youtube.com/watch?v=4WJyAYhCt1s",
                            SongTitle = "Sigh No More"
                        },
                        new
                        {
                            SongId = 2,
                            AlbumId = 1,
                            Duration = "3:37",
                            Links = "https://www.youtube.com/watch?v=fNy8llTLvuA",
                            SongTitle = "The Cave"
                        },
                        new
                        {
                            SongId = 3,
                            AlbumId = 1,
                            Duration = "3:39",
                            Links = "https://www.youtube.com/watch?v=_KCg_QEHtkY",
                            SongTitle = "Winter Winds"
                        },
                        new
                        {
                            SongId = 4,
                            AlbumId = 1,
                            Duration = "4:23",
                            Links = "https://www.youtube.com/watch?v=TFUoyz5l4aM",
                            SongTitle = "Roll Away Your Stone"
                        },
                        new
                        {
                            SongId = 5,
                            AlbumId = 1,
                            Duration = "4:14",
                            Links = "https://www.youtube.com/watch?v=ZTqgeUkPO0A",
                            SongTitle = "White Blank Page"
                        },
                        new
                        {
                            SongId = 6,
                            AlbumId = 1,
                            Duration = "4:18",
                            Links = "https://www.youtube.com/watch?v=4NouN_IxvM8",
                            SongTitle = "I Gave You All"
                        },
                        new
                        {
                            SongId = 7,
                            AlbumId = 1,
                            Duration = "4:05",
                            Links = "https://www.youtube.com/watch?v=am3WKqVX6D8",
                            SongTitle = "Little Lion Man"
                        },
                        new
                        {
                            SongId = 8,
                            AlbumId = 1,
                            Duration = "2:54",
                            Links = "https://www.youtube.com/watch?v=pSPy59xNtTU",
                            SongTitle = "Timshel"
                        },
                        new
                        {
                            SongId = 9,
                            AlbumId = 1,
                            Duration = "4:50",
                            Links = "https://www.youtube.com/watch?v=pxScXFVZHH8",
                            SongTitle = "Thistle & Weeds"
                        },
                        new
                        {
                            SongId = 10,
                            AlbumId = 1,
                            Duration = "4:13",
                            Links = "https://www.youtube.com/watch?v=DFQVtIiRDuA",
                            SongTitle = "Awake My Soul"
                        },
                        new
                        {
                            SongId = 11,
                            AlbumId = 1,
                            Duration = "4:40",
                            Links = "https://www.youtube.com/watch?v=sPSYuxVyf7E",
                            SongTitle = "Dust Bowl Dance"
                        },
                        new
                        {
                            SongId = 12,
                            AlbumId = 1,
                            Duration = "4:11",
                            Links = "https://www.youtube.com/watch?v=3jNILCzQurM",
                            SongTitle = "After the Storm"
                        },
                        new
                        {
                            SongId = 13,
                            AlbumId = 2,
                            Duration = "3:29",
                            Links = "https://www.youtube.com/watch?v=iWza_On7ajs",
                            SongTitle = "Babel"
                        },
                        new
                        {
                            SongId = 14,
                            AlbumId = 2,
                            Duration = "3:16",
                            Links = "https://www.youtube.com/watch?v=zNaM-N1NdGo",
                            SongTitle = "Whispers in the Dark"
                        },
                        new
                        {
                            SongId = 15,
                            AlbumId = 2,
                            Duration = "4:37",
                            Links = "https://www.youtube.com/watch?v=rGKfrgqWcv0",
                            SongTitle = "I Will Wait"
                        },
                        new
                        {
                            SongId = 16,
                            AlbumId = 2,
                            Duration = "4:13",
                            Links = "https://www.youtube.com/watch?v=Yemeb524Kx4",
                            SongTitle = "Holland Road"
                        },
                        new
                        {
                            SongId = 17,
                            AlbumId = 2,
                            Duration = "5:40",
                            Links = "https://www.youtube.com/watch?v=FM6EzfZQWEI",
                            SongTitle = "Ghosts That We Knew"
                        },
                        new
                        {
                            SongId = 18,
                            AlbumId = 2,
                            Duration = "5:15",
                            Links = "https://www.youtube.com/watch?v=lR5GXgC2q2M",
                            SongTitle = "Lover of the Light"
                        },
                        new
                        {
                            SongId = 19,
                            AlbumId = 2,
                            Duration = "5:21",
                            Links = "https://www.youtube.com/watch?v=9yw2_HSj87s",
                            SongTitle = "Lovers' Eyes"
                        },
                        new
                        {
                            SongId = 20,
                            AlbumId = 2,
                            Duration = "2:05",
                            Links = "https://www.youtube.com/watch?v=8KV98HB8o7o",
                            SongTitle = "Reminder"
                        },
                        new
                        {
                            SongId = 21,
                            AlbumId = 2,
                            Duration = "5:08",
                            Links = "https://www.youtube.com/watch?v=zushTvKC0PU",
                            SongTitle = "Hopeless Wanderer"
                        },
                        new
                        {
                            SongId = 22,
                            AlbumId = 2,
                            Duration = "4:16",
                            Links = "https://www.youtube.com/watch?v=mjqUXexR8Vo",
                            SongTitle = "Broken Crown"
                        },
                        new
                        {
                            SongId = 23,
                            AlbumId = 2,
                            Duration = "4:52",
                            Links = "https://www.youtube.com/watch?v=3Imwnc8Ad9M",
                            SongTitle = "Below My Feet"
                        },
                        new
                        {
                            SongId = 24,
                            AlbumId = 2,
                            Duration = "4:09",
                            Links = "https://www.youtube.com/watch?v=avT0Rj50130",
                            SongTitle = "Not With Haste"
                        },
                        new
                        {
                            SongId = 25,
                            AlbumId = 3,
                            Duration = "4:59",
                            Links = "https://www.youtube.com/watch?v=sCXkbBBG4f0",
                            SongTitle = "Heir of a Dying Day"
                        },
                        new
                        {
                            SongId = 26,
                            AlbumId = 3,
                            Duration = "4:34",
                            Links = "https://www.youtube.com/watch?v=wD20Oze5NYw",
                            SongTitle = "To Live Is to Hide"
                        },
                        new
                        {
                            SongId = 27,
                            AlbumId = 3,
                            Duration = "4:36",
                            Links = "https://www.youtube.com/watch?v=tFfchptAI3w",
                            SongTitle = "Purify"
                        },
                        new
                        {
                            SongId = 28,
                            AlbumId = 3,
                            Duration = "3:53",
                            Links = "https://www.youtube.com/watch?v=zDi1FwihzlQ",
                            SongTitle = "Senzafine"
                        },
                        new
                        {
                            SongId = 29,
                            AlbumId = 3,
                            Duration = "5:54",
                            Links = "https://www.youtube.com/watch?v=jFfEfpbH40E",
                            SongTitle = "When a Dead Man Walks"
                        },
                        new
                        {
                            SongId = 30,
                            AlbumId = 3,
                            Duration = "4:58",
                            Links = "https://www.youtube.com/watch?v=8lfcPeHM73M",
                            SongTitle = "1:19"
                        },
                        new
                        {
                            SongId = 31,
                            AlbumId = 3,
                            Duration = "5:23",
                            Links = "https://www.youtube.com/watch?v=7oIjVK08_8Y",
                            SongTitle = "Cold Heritage"
                        },
                        new
                        {
                            SongId = 32,
                            AlbumId = 3,
                            Duration = "5:29",
                            Links = "https://www.youtube.com/watch?v=lTyiPm4lJBc",
                            SongTitle = "Distant Sun"
                        },
                        new
                        {
                            SongId = 33,
                            AlbumId = 3,
                            Duration = "5:20",
                            Links = "https://www.youtube.com/watch?v=2aQDWfnOLlE",
                            SongTitle = "A Current Obsession"
                        },
                        new
                        {
                            SongId = 34,
                            AlbumId = 3,
                            Duration = "4:40",
                            Links = "https://www.youtube.com/watch?v=f_2EhXHf4bs",
                            SongTitle = "Wave of Anguish"
                        },
                        new
                        {
                            SongId = 35,
                            AlbumId = 4,
                            Duration = "4:00",
                            Links = "https://www.youtube.com/watch?v=nOuxOUYycoU",
                            SongTitle = "Swamped"
                        },
                        new
                        {
                            SongId = 36,
                            AlbumId = 4,
                            Duration = "4:46",
                            Links = "https://www.youtube.com/watch?v=4wfRHPsRGkk",
                            SongTitle = "Heaven's a Lie"
                        },
                        new
                        {
                            SongId = 37,
                            AlbumId = 4,
                            Duration = "3:50",
                            Links = "https://www.youtube.com/watch?v=EPo-0hJhOPo",
                            SongTitle = "Daylight Dancer"
                        },
                        new
                        {
                            SongId = 38,
                            AlbumId = 4,
                            Duration = "4:12",
                            Links = "https://www.youtube.com/watch?v=IOvSNweknM0",
                            SongTitle = "Humane"
                        },
                        new
                        {
                            SongId = 39,
                            AlbumId = 4,
                            Duration = "3:31",
                            Links = "https://www.youtube.com/watch?v=UDcMYJU_K7E",
                            SongTitle = "Self Deception"
                        },
                        new
                        {
                            SongId = 40,
                            AlbumId = 4,
                            Duration = "1:56",
                            Links = "https://www.youtube.com/watch?v=rpS0vVzPPLw",
                            SongTitle = "Aeon"
                        },
                        new
                        {
                            SongId = 41,
                            AlbumId = 4,
                            Duration = "4:15",
                            Links = "https://www.youtube.com/watch?v=mR-B5cjToL0",
                            SongTitle = "Tight Rope"
                        },
                        new
                        {
                            SongId = 42,
                            AlbumId = 4,
                            Duration = "4:09",
                            Links = "https://www.youtube.com/watch?v=Nw561NWK9Zg",
                            SongTitle = "The Ghost Woman and the Hunter"
                        },
                        new
                        {
                            SongId = 43,
                            AlbumId = 4,
                            Duration = "3:37",
                            Links = "https://www.youtube.com/watch?v=3ixjeXLCAiA",
                            SongTitle = "Unspoken"
                        },
                        new
                        {
                            SongId = 44,
                            AlbumId = 4,
                            Duration = "3:59",
                            Links = "https://www.youtube.com/watch?v=Nn2WzHcyn5I",
                            SongTitle = "Entwined"
                        },
                        new
                        {
                            SongId = 45,
                            AlbumId = 4,
                            Duration = "4:32",
                            Links = "https://www.youtube.com/watch?v=YSXvlOPLk3c",
                            SongTitle = "The Prophet Said"
                        },
                        new
                        {
                            SongId = 46,
                            AlbumId = 4,
                            Duration = "3:56",
                            Links = "https://www.youtube.com/watch?v=vCIJrEtjXfw",
                            SongTitle = "Angel's Punishment"
                        },
                        new
                        {
                            SongId = 47,
                            AlbumId = 4,
                            Duration = "5:01",
                            Links = "https://www.youtube.com/watch?v=SzN1bHSkpQI",
                            SongTitle = "Comalies"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.HasOne("album_collection.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("album_collection.Models.Song", b =>
                {
                    b.HasOne("album_collection.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
