// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using album_collection.Models;

namespace album_collection.Migrations
{
    [DbContext(typeof(AlbumCollectionContext))]
    [Migration("20200319143103_SongsMigration")]
    partial class SongsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            ArtistId = 1,
                            Image = "sighnomore.jpg",
                            RecordLabel = "Island Records",
                            Title = "Sigh No More"
                        },
                        new
                        {
                            AlbumId = 2,
                            ArtistId = 1,
                            Image = "babel.jpg",
                            RecordLabel = "Island Records",
                            Title = "Babel"
                        },
                        new
                        {
                            AlbumId = 3,
                            ArtistId = 2,
                            Image = "unleashedmemories.jpg",
                            RecordLabel = "Century Media",
                            Title = "Unleashed Memories"
                        },
                        new
                        {
                            AlbumId = 4,
                            ArtistId = 2,
                            Image = "comalies.jpg",
                            RecordLabel = "Century Media",
                            Title = "Comalies"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hometown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            Hometown = "London, UK",
                            Image = "mumfordsons.jpg",
                            Name = "Mumford & Sons"
                        },
                        new
                        {
                            ArtistId = 2,
                            Hometown = "Milan, Italy",
                            Image = "lacunacoil.jpg",
                            Name = "Lacuna Coil"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Links")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SongTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SongId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            AlbumId = 1,
                            Duration = "3:30",
                            Links = "link.html",
                            SongTitle = "Sigh No More"
                        },
                        new
                        {
                            SongId = 2,
                            AlbumId = 1,
                            Duration = "3:37",
                            Links = "link.html",
                            SongTitle = "The Cave"
                        },
                        new
                        {
                            SongId = 3,
                            AlbumId = 1,
                            Duration = "3:39",
                            Links = "link.html",
                            SongTitle = "Winter Winds"
                        },
                        new
                        {
                            SongId = 4,
                            AlbumId = 1,
                            Duration = "4:23",
                            Links = "link.html",
                            SongTitle = "Roll Away Your Stone"
                        },
                        new
                        {
                            SongId = 5,
                            AlbumId = 1,
                            Duration = "4:14",
                            Links = "link.html",
                            SongTitle = "White Blank Page"
                        },
                        new
                        {
                            SongId = 6,
                            AlbumId = 1,
                            Duration = "4:18",
                            Links = "link.html",
                            SongTitle = "I Gave You All"
                        },
                        new
                        {
                            SongId = 7,
                            AlbumId = 1,
                            Duration = "4:05",
                            Links = "link.html",
                            SongTitle = "Little Lion Man"
                        },
                        new
                        {
                            SongId = 8,
                            AlbumId = 1,
                            Duration = "2:54",
                            Links = "link.html",
                            SongTitle = "Timshel"
                        },
                        new
                        {
                            SongId = 9,
                            AlbumId = 1,
                            Duration = "4:50",
                            Links = "link.html",
                            SongTitle = "Thistle & Weeds"
                        },
                        new
                        {
                            SongId = 10,
                            AlbumId = 1,
                            Duration = "4:13",
                            Links = "link.html",
                            SongTitle = "Awake My Soul"
                        },
                        new
                        {
                            SongId = 11,
                            AlbumId = 1,
                            Duration = "4:40",
                            Links = "link.html",
                            SongTitle = "Dust Bowl Dance"
                        },
                        new
                        {
                            SongId = 12,
                            AlbumId = 1,
                            Duration = "4:11",
                            Links = "link.html",
                            SongTitle = "After the Storm"
                        },
                        new
                        {
                            SongId = 13,
                            AlbumId = 2,
                            Duration = "3:29",
                            Links = "link.html",
                            SongTitle = "Babel"
                        },
                        new
                        {
                            SongId = 14,
                            AlbumId = 2,
                            Duration = "3:16",
                            Links = "link.html",
                            SongTitle = "Whispers in the Dark"
                        },
                        new
                        {
                            SongId = 15,
                            AlbumId = 2,
                            Duration = "4:37",
                            Links = "link.html",
                            SongTitle = "I Will Wait"
                        },
                        new
                        {
                            SongId = 16,
                            AlbumId = 2,
                            Duration = "4:13",
                            Links = "link.html",
                            SongTitle = "Holland Road"
                        },
                        new
                        {
                            SongId = 17,
                            AlbumId = 2,
                            Duration = "5:40",
                            Links = "link.html",
                            SongTitle = "Ghosts That We Knew"
                        },
                        new
                        {
                            SongId = 18,
                            AlbumId = 2,
                            Duration = "5:15",
                            Links = "link.html",
                            SongTitle = "Lover of the Light"
                        },
                        new
                        {
                            SongId = 19,
                            AlbumId = 2,
                            Duration = "5:21",
                            Links = "link.html",
                            SongTitle = "Lovers' Eyes"
                        },
                        new
                        {
                            SongId = 20,
                            AlbumId = 2,
                            Duration = "2:05",
                            Links = "link.html",
                            SongTitle = "Reminder"
                        },
                        new
                        {
                            SongId = 21,
                            AlbumId = 2,
                            Duration = "5:08",
                            Links = "link.html",
                            SongTitle = "Hopeless Wanderer"
                        },
                        new
                        {
                            SongId = 22,
                            AlbumId = 2,
                            Duration = "4:16",
                            Links = "link.html",
                            SongTitle = "Broken Crown"
                        },
                        new
                        {
                            SongId = 23,
                            AlbumId = 2,
                            Duration = "4:52",
                            Links = "link.html",
                            SongTitle = "Below My Feet"
                        },
                        new
                        {
                            SongId = 24,
                            AlbumId = 2,
                            Duration = "4:09",
                            Links = "link.html",
                            SongTitle = "Not With Haste"
                        },
                        new
                        {
                            SongId = 25,
                            AlbumId = 3,
                            Duration = "4:59",
                            Links = "link.html",
                            SongTitle = "Heir of a Dying Day"
                        },
                        new
                        {
                            SongId = 26,
                            AlbumId = 3,
                            Duration = "4:34",
                            Links = "link.html",
                            SongTitle = "To Live Is to Hide"
                        },
                        new
                        {
                            SongId = 27,
                            AlbumId = 3,
                            Duration = "4:36",
                            Links = "link.html",
                            SongTitle = "Purify"
                        },
                        new
                        {
                            SongId = 28,
                            AlbumId = 3,
                            Duration = "3:53",
                            Links = "link.html",
                            SongTitle = "Senzafine"
                        },
                        new
                        {
                            SongId = 29,
                            AlbumId = 3,
                            Duration = "5:54",
                            Links = "link.html",
                            SongTitle = "When a Dead Man Walks"
                        },
                        new
                        {
                            SongId = 30,
                            AlbumId = 3,
                            Duration = "4:58",
                            Links = "link.html",
                            SongTitle = "1:19"
                        },
                        new
                        {
                            SongId = 31,
                            AlbumId = 3,
                            Duration = "5:23",
                            Links = "link.html",
                            SongTitle = "Cold Heritage"
                        },
                        new
                        {
                            SongId = 32,
                            AlbumId = 3,
                            Duration = "5:29",
                            Links = "link.html",
                            SongTitle = "Distant Sun"
                        },
                        new
                        {
                            SongId = 33,
                            AlbumId = 3,
                            Duration = "5:20",
                            Links = "link.html",
                            SongTitle = "A Current Obsession"
                        },
                        new
                        {
                            SongId = 34,
                            AlbumId = 3,
                            Duration = "4:40",
                            Links = "link.html",
                            SongTitle = "Wave of Anguish"
                        },
                        new
                        {
                            SongId = 35,
                            AlbumId = 4,
                            Duration = "4:00",
                            Links = "link.html",
                            SongTitle = "Swamped"
                        },
                        new
                        {
                            SongId = 36,
                            AlbumId = 4,
                            Duration = "4:46",
                            Links = "link.html",
                            SongTitle = "Heaven's a Lie"
                        },
                        new
                        {
                            SongId = 37,
                            AlbumId = 4,
                            Duration = "3:50",
                            Links = "link.html",
                            SongTitle = "Daylight Dancer"
                        },
                        new
                        {
                            SongId = 38,
                            AlbumId = 4,
                            Duration = "4:12",
                            Links = "link.html",
                            SongTitle = "Humane"
                        },
                        new
                        {
                            SongId = 39,
                            AlbumId = 4,
                            Duration = "3:31",
                            Links = "link.html",
                            SongTitle = "Self Deception"
                        },
                        new
                        {
                            SongId = 40,
                            AlbumId = 4,
                            Duration = "1:56",
                            Links = "link.html",
                            SongTitle = "Aeon"
                        },
                        new
                        {
                            SongId = 41,
                            AlbumId = 4,
                            Duration = "4:15",
                            Links = "link.html",
                            SongTitle = "Tight Rope"
                        },
                        new
                        {
                            SongId = 42,
                            AlbumId = 4,
                            Duration = "4:09",
                            Links = "link.html",
                            SongTitle = "The Ghost Woman and the Hunter"
                        },
                        new
                        {
                            SongId = 43,
                            AlbumId = 4,
                            Duration = "3:37",
                            Links = "link.html",
                            SongTitle = "Unspoken"
                        },
                        new
                        {
                            SongId = 44,
                            AlbumId = 4,
                            Duration = "3:59",
                            Links = "link.html",
                            SongTitle = "Entwined"
                        },
                        new
                        {
                            SongId = 45,
                            AlbumId = 4,
                            Duration = "4:32",
                            Links = "link.html",
                            SongTitle = "The Prophet Said"
                        },
                        new
                        {
                            SongId = 46,
                            AlbumId = 4,
                            Duration = "3:56",
                            Links = "link.html",
                            SongTitle = "Angel's Punishment"
                        },
                        new
                        {
                            SongId = 47,
                            AlbumId = 4,
                            Duration = "5:01",
                            Links = "link.html",
                            SongTitle = "Comalies"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.HasOne("album_collection.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("album_collection.Models.Song", b =>
                {
                    b.HasOne("album_collection.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
